/* Actual app handler regression, synthetic data only. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('gateway/public/index.html','utf8');
const code=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(x=>x[1]).join('\n').replace(/\nboot\(\);/,'\n');
const listeners={},elements={},storage=new Map(),messages=[];let fail=false;
const node=()=>({style:{setProperty(){}},classList:{add(){},remove(){},toggle(){}},setAttribute(){},getAttribute(){},appendChild(){},focus(){},innerHTML:''});
const c={console,Date,Math,JSON,Number,String,Array,Object,Promise,Set,Map,RegExp,URL,parseFloat,isFinite,isNaN,setTimeout:()=>0,clearTimeout(){},navigator:{},location:{protocol:'https:',origin:'https://ledger.test',hostname:'ledger.test',reload(){c.reloads++}},history:{pushState(){},replaceState(){}},window:{addEventListener(){},scrollTo(){}},document:{addEventListener(k,f){(listeners[k]??=[]).push(f)},getElementById(id){return elements[id]||null},querySelector(){return null},querySelectorAll(){return []},documentElement:node(),body:node(),createElement:node},localStorage:{getItem(k){return storage.get(k)||null},setItem(k,v){if(fail&&k==='site-ledger-v1')throw Error('quota');storage.set(k,v)},removeItem(k){storage.delete(k)}},sessionStorage:{getItem(){return null},setItem(){},removeItem(){}}};
vm.createContext(c);vm.runInContext(code,c);c.render=()=>{};c.go=()=>{};c.toast=x=>messages.push(x);c.idbPut=async()=>true;c.idbSet=async()=>true;
function reset(){c.S=c.emptyState();c.S.projects=[{id:'p',name:'โครงการทดสอบ',status:'active'}];c.U.sheet=null;c.U.draft=null;c.U.saveLock=false;c.U.expenseScanBusy=false;c.U.expenseBatchBusy=false;c.U.cloudSyncBusy=false;c.U.profilePhotoBusy=false;c.U.profilePostSaving=false;c.U.storageConflict=false;c.committedState='';c.reloads=0;fail=false;storage.clear();messages.length=0;}
function action(a,id=''){const el={dataset:{act:a,id},getAttribute(k){return k==='data-act'?a:k==='data-id'?id:null},closest(){return this}};listeners.click.forEach(f=>f({target:el,preventDefault(){},stopPropagation(){}}));}
function rows(){return c.expenseBatchItemsFromResult(c.expenseOcrNormalizeRemote({rows:[{amount:6000,date:'2026-08-04',sub:'รื้ออาคารพร้อมขนของ',cat:'ค่าแรง',paymentStatus:'paid'},{amount:17000,date:'',sub:'ก่อฉาบทับหลัง',cat:'ค่าแรง',paymentStatus:'unpaid'},{amount:54600,date:'',sub:'กระจกประตู+หน้าต่าง',cat:'ค่าของ',paymentStatus:'unpaid'}]}),'data:image/jpeg;base64,AA','labor.jpg','p','transfer','g');}
let checks=0;function test(name,fn){reset();fn();checks++;console.log('PASS',name);}
(async()=>{
test('mixed source rows retain exact amount and payment state without inferred dates or channels',()=>{const x=rows();assert.deepEqual(Array.from(x,r=>r.amount),[6000,17000,54600]);assert.deepEqual(Array.from(x,r=>r.paymentStatus),['paid','unpaid','unpaid']);assert.equal(x[1].date,'');assert.equal(x[0].pay,'');assert.equal(c.expenseBatchTotals(x).total,77600);assert.equal(c.S.tx.length,0);});
test('OCR review opens the original image for every row and labels confidence as an AI estimate',()=>{c.U.sheet={kind:'expenseBatch'};c.U.expenseBatch=rows();const out=c.sheetHtml();assert.equal((out.match(/class="expense-batch-evidence"/g)||[]).length,3);assert(out.includes('ดูรูปต้นฉบับ · แถว 1/3'));assert(out.includes('ดูรูปต้นฉบับ · แถว 3/3'));assert(out.includes('AI ประเมิน 0% · เทียบกับรูปต้นฉบับ'));assert(out.includes('เปอร์เซ็นต์ความมั่นใจเป็นค่าประเมินของ AI'));assert.equal(c.S.tx.length,0);});
test('missing date or channel blocks the whole batch without writes',()=>{c.U.expenseBatch=rows();action('expenseBatchSave');assert.equal(c.S.tx.length,0);assert.equal(c.U.expenseBatch.length,3);assert.equal(c.S.auditLog.length,0);});
test('reviewed batch splits paid and outstanding exactly and preserves shared evidence',()=>{c.U.expenseBatch=rows();c.U.expenseBatch.forEach(x=>x.date='2026-08-04');c.U.expenseBatch[0].pay='cash';action('expenseBatchSave');assert.equal(c.S.tx.length,3);assert.equal(c.S.tx.reduce((n,t)=>n+c.txPaidNet(t),0),6000);assert.equal(c.S.tx.reduce((n,t)=>n+c.txOutstandingNet(t),0),71600);assert.equal(c.S.tx[1].pay,'');assert.equal(c.S.tx[1].due,'');assert(c.S.tx.every(t=>t.ocrPaymentReviewed));assert.equal(c.S.tx[2].photo,'');assert(c.restoreParse(c.backupJson()).ok);c.U.sheet={kind:'tx',id:c.S.tx[2].id};assert(c.sheetHtml().includes('เปิดรายการที่เก็บรูปต้นฉบับชุดนี้'));});
test('unknown or partial payment is never coerced to paid or unpaid',()=>{for(const v of ['unknown','partial','จ่ายบางส่วน','',true,false])assert.equal(c.expensePaymentStatus(v),'');c.U.expenseBatch=rows();c.U.expenseBatch.forEach(x=>{x.date='2026-08-04';x.pay='cash';});c.U.expenseBatch[1].paymentStatus='';action('expenseBatchSave');assert.equal(c.S.tx.length,0);});
test('quota failure restores ledger and audit while preserving review edits',()=>{c.U.expenseBatch=rows();c.U.expenseBatch.forEach(x=>{x.date='2026-08-04';x.pay='cash';});fail=true;action('expenseBatchSave');assert.equal(c.S.tx.length,0);assert.equal(c.S.auditLog.length,0);assert.equal(c.U.expenseBatch[2].amount,54600);});
test('legacy OCR queue only inspects and opens existing records',()=>{c.S.tx=[{id:'old',pid:'p',type:'out',date:'2026-09-25',amount:100,paid:true,ocrSource:'ai',sourceRowCount:3,partner:'ว/ด/ป รายการ ค่าแรง จำนวน ราคา/หน่วย รวม หมายเหตุ'}];const before=JSON.stringify(c.S);action('ocrReviewQueue');const out=c.sheetHtml();assert(out.includes('สำรองข้อมูลก่อนแก้'));assert(out.includes('data-act="openTx"'));assert.equal(JSON.stringify(c.S),before);assert.equal(c.expenseReviewIssues(c.S.tx[0]).length,2);});
test('single OCR requires payment confirmation and explicit channel before save',()=>{c.U.draft={...c.newDraft('out','p'),amount:'100',date:'2026-08-04',ocrSource:'ai',ocrPaymentStatus:'',paid:false};c.saveTx(false);assert.equal(c.S.tx.length,0);c.U.draft.ocrPaymentStatus='paid';c.U.draft.paid=true;c.U.draft.pay='';c.saveTx(false);assert.equal(c.S.tx.length,0);});
test('PWA reload refuses every active save and review surface',()=>{assert(c.pwaCanReload());for(const key of ['draft','sheet','saveLock','expenseBatchBusy','expenseScanBusy','boqImportBusy','cloudSyncBusy','profilePostSaving','profilePhotoBusy']){c.U[key]=true;assert(!c.pwaCanReload(),key);c.U[key]=false;}});
test('BOQ ratio retains over-budget values and distinguishes missing budget',()=>{c.S.boq=[{id:'b',pid:'p',qty:1,unitPrice:100}];c.S.tx=[{pid:'p',type:'out',amount:125,paid:false,cat:'ค่าของ'}];assert.equal(c.budgetPct(c.S.projects[0]),1.25);const out=c.vProjects();assert(out.includes('125%'));assert(out.includes('รวมค้างจ่าย'));c.S.boq=[];assert(c.vProjects().includes('ยังไม่มีงบ BOQ'));});
test('onboarding and feedback entry do not write ledger or expose it',()=>{const before=JSON.stringify(c.S);action('pilotGuide');assert(c.sheetHtml().includes('เทียบรูปกับยอด'));assert.equal(JSON.stringify(c.S),before);});
reset();c.APP_BUILD={version:1049,sha:'a'.repeat(40),environment:'production'};elements.pwaCheckResult={textContent:''};c.fetch=async()=>({ok:true,text:async()=> 'var APP_BUILD='+JSON.stringify({...c.APP_BUILD,sha:'b'.repeat(40)})+';'});await c.pwaCheckUpdate();assert(elements.pwaCheckResult.textContent.includes('พร้อมใช้'));assert.equal(c.reloads,0);c.fetch=async()=>{throw Error('offline')};await c.pwaCheckUpdate();assert(elements.pwaCheckResult.textContent.includes('ยังตรวจเวอร์ชันไม่ได้'));console.log('PASS online update discovery and offline failure never reload or erase data');checks++;
require('./sync-client-modules.cjs');
console.log('PASS',checks,'v1049 reliability groups');
})().catch(e=>{console.error(e);process.exitCode=1;});
