const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('gateway/public/index.html','utf8');
const sw=fs.readFileSync('gateway/public/sw.js','utf8');
const worker=fs.readFileSync('gateway/src/worker.js','utf8');
const wr=fs.readFileSync('gateway/wrangler.toml','utf8');
const deploy=fs.readFileSync('.github/workflows/cloudflare-deploy.yml','utf8');
const legacy=fs.readFileSync('index.html','utf8');
assert(html.includes("APP_RELEASE=600,APP_CHANNEL='stable'"));
assert(html.includes('sw.js?v=600'));
assert(sw.includes('site-ledger-v600-stable-source-candidate'));
assert(html.includes('function cloudFullAcceptance'));
assert(html.includes('data-act="cloudAcceptance"'));
assert(html.includes('cloudFileDelete'));
assert(worker.includes('/v1/files/probe'));
assert(worker.includes('async function r2Probe'));
assert(worker.includes('/v1/ledger/reconcile'));
assert(worker.includes('async function productionPlatformStatus'));
assert(worker.includes('productionReady'));
assert(worker.includes('LEDGER_REVISION_CONFLICT'));
assert(worker.includes('ledger-restore-previous'));
assert(wr.includes('binding = "LEDGER_DB"'));
assert(wr.includes('binding = "LEDGER_FILES"'));
assert(wr.includes('OCR_PROVIDER = "gemini"'));
assert(deploy.includes('CLOUDFLARE_API_TOKEN'));
assert(deploy.includes('CLOUDFLARE_ACCOUNT_ID'));
assert(deploy.includes('OCR_API_KEY'));
assert(!/Access-Control-Allow-Origin['"]?\s*:\s*['"]\*/.test(worker));
assert(legacy.includes('LEGACY RECOVERY ONLY'));
assert(html.includes('site-ledger-v1'));
assert(html.includes('site-ledger-db'));
console.log('PASS v600 stable source candidate contract');
