const MAX_BODY_BYTES=3*1024*1024,WINDOW_MS=60_000,PROTOCOL_VERSION='1';
const buckets=new Map(),idempotency=new Map();
function requestId(r){const x=r.headers.get('X-AREA-Request-ID')||'';return /^[A-Za-z0-9._:-]{8,96}$/.test(x)?x:crypto.randomUUID();}
function json(data,status=200,origin='',rid=''){const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Vary':'Origin','X-AREA-Gateway-Version':PROTOCOL_VERSION};if(rid)headers['X-AREA-Request-ID']=rid;if(origin){headers['Access-Control-Allow-Origin']=origin;headers['Access-Control-Allow-Methods']='POST, OPTIONS';headers['Access-Control-Allow-Headers']='Content-Type, X-AREA-Gateway-Version, X-AREA-Request-ID';headers['Access-Control-Expose-Headers']='X-AREA-Gateway-Version, X-AREA-Request-ID';headers['Access-Control-Max-Age']='600';}return new Response(status===204?null:JSON.stringify(data),{status,headers});}
function allowedOrigins(env){return String(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);}
function corsOrigin(r,env){const o=r.headers.get('Origin')||'';if(!o)return '';const self=new URL(r.url).origin;return o===self||allowedOrigins(env).includes(o)?o:'';}
function protocolOk(r){return r.headers.get('X-AREA-Gateway-Version')===PROTOCOL_VERSION;}
function clientKey(r){return r.headers.get('CF-Connecting-IP')||'unknown';}
async function durableCall(binding,path,body){if(!binding)return null;const id=binding.idFromName(body.key),stub=binding.get(id),res=await stub.fetch('https://internal/'+path,{method:'POST',body:JSON.stringify(body)});return res.ok?res.json():null;}
async function rateAllowed(r,env){const limit=Math.max(1,Math.min(120,Number(env.RATE_LIMIT_PER_MINUTE)||20)),key=clientKey(r);const durable=await durableCall(env.GATEWAY_STATE,'rate',{key,limit,windowMs:WINDOW_MS});if(durable)return durable.allowed===true;const now=Date.now(),old=buckets.get(key);if(!old||now-old.start>=WINDOW_MS){buckets.set(key,{start:now,count:1});return true;}old.count++;return old.count<=limit;}
async function readJson(r){const len=Number(r.headers.get('Content-Length')||0);if(len&&len>MAX_BODY_BYTES)throw Error('PAYLOAD_TOO_LARGE');const text=await r.text();if(text.length>MAX_BODY_BYTES)throw Error('PAYLOAD_TOO_LARGE');return JSON.parse(text);}
function validateExpense(b){const image=b&&b.image;if(typeof image!=='string'||!/^data:image\/(jpeg|png|webp);base64,/i.test(image))throw Error('INVALID_IMAGE');return {image,lang:'tha+eng'};}
function providerConfig(env){const kind=String(env.OCR_PROVIDER||'generic').toLowerCase();if(!['generic','gemini'].includes(kind))throw Error('PROVIDER_UNSUPPORTED');const model=String(env.GEMINI_MODEL||'gemini-2.5-flash').trim();return {kind,model,url:kind==='gemini'?'https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(model)+':generateContent':String(env.OCR_UPSTREAM_URL||''),key:String(env.OCR_API_KEY||''),timeout:Math.max(3000,Math.min(20000,Number(env.PROVIDER_TIMEOUT_MS)||10000)),retries:Math.max(0,Math.min(1,Number(env.PROVIDER_RETRIES)||1))};}
function providerReady(env){try{const p=providerConfig(env);return !!p.key&&(p.kind==='gemini'||!!p.url);}catch(_){return false;}}
function providerRequest(p,payload,rid){if(p.kind==='gemini'){const m=String(payload.image||'').match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/i);if(!m)throw Error('INVALID_IMAGE');const prompt='อ่านข้อความจากใบเสร็จ/บิลภาษาไทยหรืออังกฤษให้ครบ แล้วตอบ JSON เท่านั้น: {"text":"ข้อความ OCR ทั้งหมด","amount":ยอดสุทธิเป็นตัวเลขหรือ 0,"cat":"หมวดรายจ่ายสั้นๆ","sub":"รายละเอียดสั้นๆ","partner":"ชื่อร้าน/คู่ค้า"} ห้ามเดาข้อมูลที่มองไม่เห็น';return {url:p.url,headers:{'Content-Type':'application/json','x-goog-api-key':p.key,'X-AREA-Request-ID':rid},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt},{inline_data:{mime_type:m[1].toLowerCase(),data:m[2]}}]}],generationConfig:{responseMimeType:'application/json',temperature:0}})};}return {url:p.url,headers:{'Content-Type':'application/json','Authorization':'Bearer '+p.key,'X-AREA-Request-ID':rid},body:JSON.stringify(payload)};}
function cleanExpense(data){if(!data||typeof data!=='object'||Array.isArray(data))throw Error('PROVIDER_INVALID_RESPONSE');const amount=Number(data.amount)||0;if(!isFinite(amount)||amount<0)throw Error('PROVIDER_INVALID_RESPONSE');return {text:String(data.text||'').slice(0,20000),amount,cat:String(data.cat||'ค่าของ').slice(0,80),sub:String(data.sub||'').slice(0,160),partner:String(data.partner||'').slice(0,160)};}
function geminiExpense(data){const parts=data&&data.candidates&&data.candidates[0]&&data.candidates[0].content&&data.candidates[0].content.parts,text=Array.isArray(parts)?parts.map(x=>x&&x.text||'').join('').trim():'';if(!text)throw Error('PROVIDER_INVALID_RESPONSE');try{return cleanExpense(JSON.parse(text.replace(/^\`\`\`(?:json)?\s*/i,'').replace(/\s*\`\`\`$/,'')));}catch(e){if(String(e&&e.message)==='PROVIDER_INVALID_RESPONSE')throw e;throw Error('PROVIDER_INVALID_RESPONSE');}}
function retryableStatus(s){return s===408||s===429||s>=500;}
async function providerFetch(p,payload,rid){let last;for(let attempt=0;attempt<=p.retries;attempt++){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),p.timeout);try{const rq=providerRequest(p,payload,rid),res=await fetch(rq.url,{method:'POST',headers:rq.headers,body:rq.body,signal:ctrl.signal});if(res.ok)return res;if(!retryableStatus(res.status)||attempt>=p.retries)throw Error('PROVIDER_HTTP_'+res.status);last=Error('PROVIDER_HTTP_'+res.status);}catch(e){last=e;if(attempt>=p.retries||String(e&&e.message||'').startsWith('PROVIDER_HTTP_')&&!retryableStatus(Number(String(e.message).split('_').pop())))throw e;}finally{clearTimeout(timer);}}throw last||Error('PROVIDER_FAILED');}
async function expenseOcr(payload,env,rid){const p=providerConfig(env);if(!p.key||(p.kind==='generic'&&!p.url))throw Error('PROVIDER_NOT_CONFIGURED');const res=await providerFetch(p,payload,rid),data=await res.json();return p.kind==='gemini'?geminiExpense(data):cleanExpense(data);}
async function idemGet(env,key){const d=await durableCall(env.GATEWAY_STATE,'idem-get',{key,windowMs:WINDOW_MS});if(d)return d.hit?d.value:null;const x=idempotency.get(key);if(!x)return null;if(Date.now()-x.at>WINDOW_MS){idempotency.delete(key);return null;}return x.value;}
async function idemSet(env,key,value){const d=await durableCall(env.GATEWAY_STATE,'idem-set',{key,windowMs:WINDOW_MS,value});if(d)return;idempotency.set(key,{at:Date.now(),value});if(idempotency.size>500)idempotency.delete(idempotency.keys().next().value);}
function auditMeta(rid,origin,status,started,provider){return {requestId:rid,origin,status,provider,durationMs:Date.now()-started,at:new Date().toISOString()};}
async function audit(env,meta){if(!env.GATEWAY_AUDIT)return;try{await env.GATEWAY_AUDIT.put('audit/'+meta.at+'/'+meta.requestId+'.json',JSON.stringify(meta),{httpMetadata:{contentType:'application/json'}});}catch(_){}}
export class GatewayState {
  constructor(state){this.state=state;}
  async fetch(request){
    const path=new URL(request.url).pathname,body=await request.json(),now=Date.now(),storage=this.state.storage;
    if(path==='/rate'){
      const k='rate:'+body.key,old=await storage.get(k),windowMs=Math.max(1000,+body.windowMs||WINDOW_MS),limit=Math.max(1,+body.limit||20);
      const next=!old||now-old.start>=windowMs?{start:now,count:1}:{start:old.start,count:old.count+1};
      await storage.put(k,next);await storage.setAlarm(now+windowMs*2);
      return json({allowed:next.count<=limit});
    }
    if(path==='/idem-get'){
      const ik='idem:'+body.key,x=await storage.get(ik),windowMs=Math.max(1000,+body.windowMs||WINDOW_MS);if(!x)return json({hit:false});if(now-x.at>windowMs){await storage.delete(ik);return json({hit:false});}
      return json({hit:true,value:x.value});
    }
    if(path==='/idem-set'){
      const windowMs=Math.max(1000,+body.windowMs||WINDOW_MS);await storage.put('idem:'+body.key,{at:now,value:body.value});await storage.setAlarm(now+windowMs);return json({ok:true});
    }
    return json({error:'STATE_ROUTE_NOT_FOUND'},404);
  }
  async alarm(){await this.state.storage.deleteAll();}
}
export default{async fetch(request,env){const started=Date.now(),url=new URL(request.url),rid=requestId(request);if(url.pathname==='/health'&&request.method==='GET')return json({ok:true,service:'area-ledger-ai-gateway',protocol:PROTOCOL_VERSION,providerConfigured:providerReady(env),durableState:!!env.GATEWAY_STATE,auditSink:!!env.GATEWAY_AUDIT},200,'',rid);if(url.pathname==='/ready'&&request.method==='GET'){const providerConfigured=providerReady(env),durableState=!!env.GATEWAY_STATE,allowedOriginCount=allowedOrigins(env).length,ready=providerConfigured&&durableState;return json({ok:ready,service:'area-ledger-ai-gateway',protocol:PROTOCOL_VERSION,providerConfigured,durableState,sameOriginAllowed:true,allowedOriginCount,auditSink:!!env.GATEWAY_AUDIT},ready?200:503,'',rid);}const origin=corsOrigin(request,env);if(request.method==='OPTIONS')return origin?json({ok:true,protocol:PROTOCOL_VERSION},204,origin,rid):json({error:'ORIGIN_DENIED'},403,'',rid);if(url.pathname!=='/v1/ocr/expense'||request.method!=='POST')return json({error:'NOT_FOUND'},404,'',rid);if(!origin)return json({error:'ORIGIN_DENIED'},403,'',rid);if(!protocolOk(request))return json({error:'PROTOCOL_VERSION_REQUIRED',protocol:PROTOCOL_VERSION},426,origin,rid);if(!(await rateAllowed(request,env)))return json({error:'RATE_LIMITED'},429,origin,rid);const key=origin+'|'+rid,cached=await idemGet(env,key);if(cached)return json(cached,200,origin,rid);let status=200;try{const payload=validateExpense(await readJson(request)),result=await expenseOcr(payload,env,rid);await idemSet(env,key,result);return json(result,200,origin,rid);}catch(e){const code=e&&e.name==='AbortError'?'PROVIDER_TIMEOUT':String(e&&e.message||'GATEWAY_ERROR');status=code==='PAYLOAD_TOO_LARGE'?413:code==='INVALID_IMAGE'?400:code==='PROVIDER_NOT_CONFIGURED'?503:code==='PROVIDER_UNSUPPORTED'?501:code==='PROVIDER_TIMEOUT'?504:502;return json({error:code},status,origin,rid);}finally{await audit(env,auditMeta(rid,origin,status,started,String(env.OCR_PROVIDER||'generic')));}}};
